"""Asset-specific parameter configurations.

Generated by scripts/multi_asset_validation.py.
Loaded by paper trader and live signal engine.
"""
import json
from pathlib import Path
from typing import Any

_CONFIG_PATH = Path(__file__).parent / "asset_params.json"
_CACHE: dict | None = None


def load_asset_config() -> dict[str, Any]:
    global _CACHE
    if _CACHE is not None:
        return _CACHE
    if not _CONFIG_PATH.exists():
        return {}
    with open(_CONFIG_PATH) as f:
        _CACHE = json.load(f)
    return _CACHE


def get_best_strategy(asset: str) -> str | None:
    cfg = load_asset_config().get("assets", {}).get(asset, {})
    return cfg.get("best_strategy")


def get_strategy_params(asset: str, strategy: str) -> dict[str, Any]:
    cfg = load_asset_config().get("assets", {}).get(asset, {})
    return cfg.get("strategies", {}).get(strategy, {}).get("params", {})


def get_asset_class(asset: str) -> str:
    cfg = load_asset_config().get("assets", {}).get(asset, {})
    return cfg.get("asset_class", "unknown")


def list_validated_assets() -> list[str]:
    return list(load_asset_config().get("assets", {}).keys())


def get_production_ready_combos(min_sharpe: float = 0.5,
                                 min_wf_efficiency: float = 0.5) -> list[tuple[str, str, dict]]:
    """Get (asset, strategy, metrics) tuples ready for production."""
    cfg = load_asset_config()
    ready = []
    for asset, ac in cfg.get("assets", {}).items():
        for strat, m in ac.get("strategies", {}).items():
            if m.get("sharpe", 0) >= min_sharpe and m.get("wf_efficiency", 0) >= min_wf_efficiency:
                ready.append((asset, strat, m))
    return sorted(ready, key=lambda x: x[2]["sharpe"], reverse=True)
